root: true

extends:
  - '@form8ion'
  - '@form8ion/cucumber'
  - '@form8ion/mocha'

overrides:
  - files:
      - vitest.config.js
      - templates/config.js
    rules:
      import/no-unresolved: off
