name: Node.js CI
'on':
  push:
    branches:
      - master
      - beta
      - renovate/**
  pull_request:
    types:
      - opened
      - synchronize
env:
  FORCE_COLOR: 1
  NPM_CONFIG_COLOR: always
jobs:
  verify-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node:
          - 16.0.0
          - 16
          - 18
          - 19
    steps:
      - uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3
      - name: Setup node
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3
        with:
          cache: npm
          node-version: ${{ matrix.node }}
      - run: npm clean-install
      - run: npm test
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3
      - name: Setup node
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3
        with:
          node-version-file: .nvmrc
          cache: npm
      - run: npm clean-install
      - run: npm test
      - uses: codecov/codecov-action@9b87723d6ac0be351efc7242ba5ec28fa641c77c
  release:
    needs:
      - verify
      - verify-matrix
    uses: form8ion/.github/.github/workflows/release-package.yml@master
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
